version: '2'

services:
    drone-server:
        image: drone/drone:0.8
        ports: 
            - 8082:8000
            - 9000

        volumes: 
            - /var/lib/drone:/var/lib/drone/
        restart: always
        env_file: .env
        environment:
            - DRONE_OPEN=true
            - DRONE_HOST=${DRONE_HOST}
            - DRONE_ADMIN=${GITHUB_NAME}
            - DRONE_GITHUB=true
            - DRONE_GITHUB_CLIENT=${DRONE_GITHUB_CLIENT}
            - DRONE_GITHUB_SECRET=${DRONE_GITHUB_SECRET}
            - DRONE_SECRET=${DRONE_SECRET}
    drone-agent:
        image: drone/agent:0.8

        command: agent
        restart: always
        depends_on:
            - drone-server

        volumes:
           - /var/run/docker.sock:/var/run/docker.sock
        env_file: .env
        environment:
            - DRONE_SERVER=drone-server:9000
            - DRONE_SECRET=${DRONE_SECRET}
